project:
  type: website

website:
  title: "GeoGirls"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: intro.qmd
        text: Introduction

format:
  html:
  
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

